export const bannedWords = [
    'coon',
    'coons',
    'che-che',
    'che-ches',
    'faggot',
    'faggots',
    'fag',
    'fags',
    'gringo',
    'gringos',
    'jap',
    'japs',
    'kike',
    'kikes',
    'kyke',
    'kykes',
    'kraut',
    'krauts',
    'niglet',
    'niglets',
    'nigger',
    'niggers',
    'porch monkey',
    'porch monkeys',
    'porch monkies',
    'sand nigger',
    'sand niggers',
    'tranny',
    'trannys',
    'trannies',
    'zipperhead',
    'zipperheads',
    'zipper head',
    'zipper heads',
];